services:
  auth_system_db:
    image: postgres:15-alpine
    container_name: auth_system_db
    env_file:
      - ./.env
    ports:
      - "5435:5432"
    volumes:
      - auth_system_db_data:/var/lib/postgresql/data

  auth_system_api:
    build: .
    container_name: auth_system_api
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - auth_system_db

volumes:
  auth_system_db_data: